# Generated by Django 2.1.7 on 2019-03-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='rules',
            field=models.TextField(default='There are no rules'),
            preserve_default=False,
        ),
    ]
