# Generated by Django 2.2 on 2019-04-12 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('date_battle', '0002_challenge_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('streak', models.IntegerField()),
                ('prev_date', models.DateField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='date_battle.Challenge')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
