# Generated by Django 2.2 on 2019-04-24 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('date_battle', '0003_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='prev_date',
            new_name='today',
        ),
        migrations.AlterField(
            model_name='entries',
            name='streak',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='user_challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='date_battle.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
